### ISSUE TITLE
Question about subtyping

### ISSUE THREAD

**Issue by andreypopp** [Gabriel439/grace#26]
Hello, I'm studying Grace and curious about the way it handles type inference with subtyping.

So consider this case which TYPES ok:
```
; cabal run -- grace interpret --annotate - <<< '[{answer: null}, {answer: 42}]'
[ { "answer": null }, { "answer": 42 } ] : List { answer: Optional Natural }
```
and this which FAILS:
```
; cabal run -- grace interpret --annotate - <<< '[{answer: 42}, {answer: null}]'
Not a subtype
...
```

So the depending on the order of elements in the list it either succeeds or fails which can be then fixed (suggested by the README) by adding a type annotation with an existential `List ?`:
```
; cabal run -- grace interpret --annotate - <<< '[{answer: 42}, {answer: null}] : List ?'
[ { "answer": 42 }, { "answer": null } ] : List ?
```

I think this can be a bit confusing to users (that in those two similar cases they either required or not to add type annotations). Do you think it's worth fixing and/or possible to fix by synthesising `List ?` type for `List` constructor?

**Comment by Gabriel439** [comment]
Yeah, I think that would work well (i.e. falling back to `?` as the element type if type-checking the `List` fails the first time)

I have to fix another type-checking bug first, because I realized there was something wrong in the course of trying to implement this

**Comment by andreypopp** [comment]
Reading more on [Bidirectional Typing][bidi], which discusses "Complete and Easy" (more specifically section 5.1.1 "Greedy Instantiation"), mentions a similar problem — the first seen argument "wins" and instantiates the polymorphic variable — this doesn't work well with other forms of subtyping than the polymorphic one.

One approach I've seen which handles such subtyping with bidirectional type checking is [Local Type Inference][local-ti] paper. They propose to collect a set of constraints over variables (lower and upper bounds) during synthesising/checking applications and solve them to instantiate type variables.

[bidi]: https://arxiv.org/pdf/1908.05839.pdf
[local-ti]: https://www.cs.tufts.edu/comp/150FP/archive/benjamin-pierce/lti-toplas.pdf

**Comment by Gabriel439** [comment]
So I managed to fix the bug with typed holes that I mentioned: https://github.com/Gabriel439/grace/pull/27

However, it turns out that my proposed fix doesn't work, for the reasons you mentioned.  The hole will get instantiated greedily to the first element in the list it encounters, so you end up with the exact same problem.

I don't think this is fixable short of overhauling the type checker to use something other than bidirectional type inference.

**Comment by andreypopp** [comment]
> I don't think this is fixable short of overhauling the type checker to use something other than bidirectional type inference.

Just to clarify — the ["Local Type Inference"][local-ti] paper uses bidirectional type checking (in fact I've seen many cite it as the first paper describing it, though they themselves say that this is folklore). 

But nevertheless, you're right, the change is probably not so trivial and I'm not sure how well it can be combined with polymorphic subtyping which Grace has now. So this issue can probably be closed.

By the way — do you think higher rank polymorphism is important for a configuration language (I don't have a good intuition where it can be used)?

[local-ti]: https://dl.acm.org/doi/abs/10.1145/345099.345100
