### ISSUE TITLE
Confusing claim on parsing performance

### ISSUE THREAD

**Issue by int-index** [Gabriel439/grace#31]
The README says: “Grace uses a lexer in conjunction with an LR parsing package”. But I looked at the sources and it’s using Earley, which is not LR.

Further, the README also claims “you can easily extend or amend Grace's grammar without taking special precautions to avoid performance pitfalls”, but worst-case time complexity for an Earley parser is cubic, so that doesn’t seem true either.

Perhaps you initially used `happy` or some other LR parser generator where those claims were true? Should the README be updated?

**Comment by Gabriel439** [comment]
Yeah, I did initially use `happy`.  What is the correct term to use instead of LR Parser?

I think it's fine to say that it avoids performance pitfalls, though, for typical programming language grammars

**Comment by Gabriel439** [comment]
To clarify why I think it's fine to say that it avoids performance pitfalls: according to the `Earley` package description it say that:

> The parser implements an optimisation similar to that presented in Joop M.I.M Leo's paper *A general context-free parsing algorithm running in linear time on every LR(k) grammar without using lookahead*, which removes indirections in sequences of non-ambiguous backpointers between item sets.

So my understanding is that it will run in linear time on any programming language which can be parsed by an LR parser, which I believe is most programming languages.

**Comment by int-index** [comment]
> I think it's fine to say that it avoids performance pitfalls, though, for typical programming language grammars
> ...
> So my understanding is that it will run in linear time on any programming language which can be parsed by an LR parser, which I believe is most programming languages.

With parser combinators one can also write a linear time parser (if careful), but it is not enforced. With `happy` you are guaranteed to get a linear time parser. Perhaps Earley is somewhere in the middle: it is less likely to be accidentally non-linear than with parser combinators, yet with `happy` it wouldn’t be possible at all.

> What is the correct term to use instead of LR Parser?

Earley parser :-) At least that’s my understanding of it, it’s an algorithm which is distinct from LR and LL. I actually don’t know it well enough to tell how similar/different they are, but cursory reading seems to indicate that they’re treated as different parsing approaches in literature.

**Comment by Gabriel439** [comment]
Does #32 address your concerns?
